// To add a new testimonial, upload your image to the `public/images` folder
// and then add its path to this list.
// For example: "/images/new-testimonial.png"

export const testimonialImages = [
  "/images/testimonial-1.png",
  "/images/testimonial-2.png",
  "/images/testimonial-3.png",
  "/images/testimonial-4.png",
  "/images/testimonial-5.png",
  "/images/testimonial-6.png",
  "/images/testimonial-7.png",
  "/images/testimonial-8.png",
  "/images/testimonial-9.png",
  "/images/testimonial-10.png",
  "/images/testimonial-11.png",
  "/images/testimonial-12.png",
]

export interface TestimonialData {
  id: string
  type: "image" | "video"
  src: string
  category: "knee-pain" | "shoulder-pain" | "back-pain" | "arthritis" | "general" | "elderly"
  title: string
  description?: string
  customerName?: string
  age?: number
  location?: string
  verified: boolean
  featured: boolean
  dateAdded: string
}

export const structuredTestimonials: TestimonialData[] = [
  {
    id: "img-001",
    type: "image",
    src: "/images/testimonial-1.png",
    category: "knee-pain",
    title: "膝盖疼痛3周见效",
    description: "用了3周，膝盖疼痛明显减轻，上下楼梯轻松多了",
    customerName: "陈女士",
    age: 62,
    location: "新加坡",
    verified: true,
    featured: true,
    dateAdded: "2024-07-20",
  },
  {
    id: "img-002",
    type: "image",
    src: "/images/testimonial-2.png",
    category: "shoulder-pain",
    title: "肩膀僵硬得到缓解",
    description: "僵硬的肩膀松了很多，抬手很轻松",
    customerName: "李先生",
    age: 58,
    location: "新加坡",
    verified: true,
    featured: true,
    dateAdded: "2024-07-18",
  },
  {
    id: "img-003",
    type: "image",
    src: "/images/testimonial-3.png",
    category: "back-pain",
    title: "腰痛问题改善",
    description: "长期腰痛得到很好的缓解，睡眠质量也提高了",
    customerName: "王女士",
    age: 45,
    location: "新加坡",
    verified: true,
    featured: false,
    dateAdded: "2024-07-15",
  },
  {
    id: "img-004",
    type: "image",
    src: "/images/testimonial-4.png",
    category: "arthritis",
    title: "关节炎症状减轻",
    description: "关节炎引起的疼痛和肿胀都有明显改善",
    customerName: "张先生",
    age: 67,
    location: "新加坡",
    verified: true,
    featured: true,
    dateAdded: "2024-07-12",
  },
  {
    id: "img-005",
    type: "image",
    src: "/images/testimonial-5.png",
    category: "general",
    title: "整体疼痛缓解",
    description: "多处关节疼痛都得到了很好的缓解",
    customerName: "林女士",
    age: 54,
    location: "新加坡",
    verified: true,
    featured: false,
    dateAdded: "2024-07-10",
  },
  {
    id: "img-006",
    type: "image",
    src: "/images/testimonial-6.png",
    category: "elderly",
    title: "乐龄人士的选择",
    description: "年纪大了各种疼痛，这个产品很温和有效",
    customerName: "黄伯伯",
    age: 72,
    location: "新加坡",
    verified: true,
    featured: true,
    dateAdded: "2024-07-08",
  },
  {
    id: "img-007",
    type: "image",
    src: "/images/testimonial-7.png",
    category: "knee-pain",
    title: "膝盖疼痛快速缓解",
    description: "10秒就能感受到热感，膝盖疼痛很快缓解",
    verified: true,
    featured: false,
    dateAdded: "2024-07-05",
  },
  {
    id: "img-008",
    type: "image",
    src: "/images/testimonial-8.png",
    category: "shoulder-pain",
    title: "肩颈疼痛改善",
    description: "长期电脑工作导致的肩颈疼痛得到很好缓解",
    verified: true,
    featured: false,
    dateAdded: "2024-07-03",
  },
  {
    id: "img-009",
    type: "image",
    src: "/images/testimonial-9.png",
    category: "back-pain",
    title: "腰部疼痛缓解",
    description: "腰部疼痛明显减轻，工作效率也提高了",
    verified: true,
    featured: false,
    dateAdded: "2024-07-01",
  },
  {
    id: "img-010",
    type: "image",
    src: "/images/testimonial-10.png",
    category: "arthritis",
    title: "风湿关节炎改善",
    description: "风湿关节炎的症状得到很好控制",
    verified: true,
    featured: true,
    dateAdded: "2024-06-28",
  },
  {
    id: "img-011",
    type: "image",
    src: "/images/testimonial-11.png",
    category: "general",
    title: "全身疼痛缓解",
    description: "多年的慢性疼痛问题得到很好改善",
    verified: true,
    featured: false,
    dateAdded: "2024-06-25",
  },
  {
    id: "img-012",
    type: "image",
    src: "/images/testimonial-12.png",
    category: "elderly",
    title: "老年疼痛管理",
    description: "适合老年人使用，安全有效",
    verified: true,
    featured: false,
    dateAdded: "2024-06-22",
  },
]

export const videoTestimonials: TestimonialData[] = [
  {
    id: "vid-001",
    type: "video",
    src: "/videos/testimonial-1.mp4",
    category: "knee-pain",
    title: "膝盖疼痛康复分享",
    description: "客户亲自分享膝盖疼痛的康复过程",
    customerName: "刘女士",
    age: 59,
    verified: true,
    featured: true,
    dateAdded: "2024-07-15",
  },
  {
    id: "vid-002",
    type: "video",
    src: "/videos/testimonial-2.mp4",
    category: "arthritis",
    title: "关节炎治疗心得",
    description: "多年关节炎患者的使用心得分享",
    customerName: "周先生",
    age: 64,
    verified: true,
    featured: true,
    dateAdded: "2024-07-10",
  },
  {
    id: "vid-003",
    type: "video",
    src: "/videos/testimonial-3.mp4",
    category: "back-pain",
    title: "腰痛康复经历",
    description: "腰痛患者的康复经历分享",
    verified: true,
    featured: false,
    dateAdded: "2024-07-05",
  },
  {
    id: "vid-004",
    type: "video",
    src: "/videos/testimonial-4.mp4",
    category: "shoulder-pain",
    title: "肩膀疼痛改善",
    description: "肩膀疼痛改善的真实体验",
    verified: true,
    featured: false,
    dateAdded: "2024-06-30",
  },
  {
    id: "vid-005",
    type: "video",
    src: "/videos/testimonial-5.mp4",
    category: "elderly",
    title: "乐龄用户体验",
    description: "乐龄用户的使用体验分享",
    verified: true,
    featured: true,
    dateAdded: "2024-06-25",
  },
]

export const categoryLabels = {
  "knee-pain": "膝盖疼痛",
  "shoulder-pain": "肩膀疼痛",
  "back-pain": "腰背疼痛",
  arthritis: "关节炎",
  general: "综合疼痛",
  elderly: "乐龄专用",
}
